export const TEST = 'TEST'
export const SHOW_MENU_TOPBAR = 'SHOW_MENU_TOPBAR'

//customer
export const RECEIVE_CUSTOMER = 'RECEIVE_CUSTOMER';
export const GET_CUSTOMERS = 'GET_CUSTOMERS';
export const RECEIVE_CUSTOMERS = 'RECEIVE_CUSTOMERS';
export const CUSTOMER_FETCHING = 'CUSTOMER_FETCHING';
export const CUSTOMER_IS_EMPTY = 'CUSTOMER_IS_EMPTY';

//user || staff
export const RECEIVE_ACCESS_TOKEN = 'RECEIVE_ACCESS_TOKEN';
export const RECEIVE_USER_ACCOUNT = 'RECEIVE_USER_ACCOUNT';
export const RECEIVE_STAFF = 'RECEIVE_STAFF';
export const RECEIVE_STAFFS = 'RECEIVE_STAFFS';

//product || service
export const RECEIVE_PRODUCT_SERVICE = 'RECEIVE_PRODUCT_SERVICE';
export const RECEIVE_PRODUCT = 'RECEIVE_PRODUCT';
export const RECEIVE_SERVICE = 'RECEIVE_SERVICE';
export const USES_FETCHING = 'USES_FETCHING';
export const USES_IS_EMPTY = 'USES_IS_EMPTY';

//location
export const LOCATION_RECEIVE_CITY = 'LOCATION_RECEIVE_CITY';
export const LOCATION_RECEIVE_WARD = 'LOCATION_RECEIVE_WARD';
export const CITY_CALLING_API = 'CITY_CALLING_API';

//main-card
export const MAIN_CARD_FETCHING = 'MAIN_CARD_FETCHING';
export const MAIN_CARD_IS_EMPTY = 'MAIN_CARD_IS_EMPTY';
export const SHOW_MODAL_MAIN_CARD = 'SHOW_MODAL_MAIN_CARD';

export const SHOW_MAIN_CARD_FILTER = 'SHOW_MAIN_CARD_FILTER';
// product
export const PRODUCT_FETCHING = 'PRODUCT_FETCHING';
export const PRODUCT_IS_EMPTY = 'PRODUCT_IS_EMPTY';
