export const TEST = 'TEST'
export const SHOW_MENU_TOPBAR = 'SHOW_MENU_TOPBAR'

//customer
export const RECEIVE_CUSTOMER = 'RECEIVE_CUSTOMER';
export const GET_CUSTOMERS = 'GET_CUSTOMERS';
export const RECEIVE_CUSTOMERS = 'RECEIVE_CUSTOMERS';
export const CUSTOMER_FETCHING = 'CUSTOMER_FETCHING';
export const CUSTOMER_IS_EMPTY = 'CUSTOMER_IS_EMPTY';

//user || staff
export const RECEIVE_ACCESS_TOKEN = 'RECEIVE_ACCESS_TOKEN';
export const RECEIVE_USER_ACCOUNT = 'RECEIVE_USER_ACCOUNT';
export const RECEIVE_STAFF = 'RECEIVE_STAFF';
export const RECEIVE_STAFFS = 'RECEIVE_STAFFS';
export const STAFF_FETCHING = 'STAFF_FETCHING';
export const STAFF_IS_EMPTY = 'STAFF_IS_EMPTY';
export const STAFF_BY_REPAIRMAN = 'STAFF_BY_REPAIRMAN';

//product || service
export const RECEIVE_PRODUCT_SERVICE = 'RECEIVE_PRODUCT_SERVICE';
export const RECEIVE_PRODUCT = 'RECEIVE_PRODUCT';
export const RECEIVE_SERVICE = 'RECEIVE_SERVICE';
export const PRODUCT_FETCHING = 'PRODUCT_FETCHING';
export const PRODUCT_IS_EMPTY = 'PRODUCT_IS_EMPTY';

//location
export const LOCATION_RECEIVE_CITY = 'LOCATION_RECEIVE_CITY';
export const LOCATION_RECEIVE_WARD = 'LOCATION_RECEIVE_WARD';
export const CITY_CALLING_API = 'CITY_CALLING_API';

//main-card
export const MAIN_CARD_FETCHING = 'MAIN_CARD_FETCHING';
export const MAIN_CARD_IS_EMPTY = 'MAIN_CARD_IS_EMPTY';
export const SHOW_MAIN_CARD_FILTER = 'SHOW_MAIN_CARD_FILTER';
export const MAIN_CARD_FILTER_INFO = 'MAIN_CARD_FILTER_INFO';
export const CHANGE_MAIN_CARD_FILTER_INFO = 'CHANGE_MAIN_CARD_FILTER_INFO';
export const RECEIVE_MAIN_CARDS = 'RECEIVE_MAIN_CARDS';
export const RECEIVE_MAIN_CARD = 'RECEIVE_MAIN_CARD';


//History Main Card
export const RECEIVE_HiSTORY_MAIN_CARD = 'RECEIVE_HiSTORY_MAIN_CARD';
export const GET_HISTORY_MAIN_CARDS = 'GET_HISTORY_MAIN_CARDS';
export const RECEIVE_HISTORY_MAIN_CARDS = 'RECEIVE_HISTORY_MAIN_CARDS';
export const HISTORY_MAIN_CARD_FETCHING = 'HISTORY_MAIN_CARD_FETCHING';
export const HISTORY_MAIN_CARD_IS_EMPTY = 'HISTORY_MAIN_CARD_IS_EMPTY';

//staff history Main Card
export const RECEIVE_STAFF_HiSTORY_MAIN_CARD = 'RECEIVE_STAFF_HiSTORY_MAIN_CARD';
export const GET_STAFF_HISTORY_MAIN_CARDS = 'GET_STAFF_HISTORY_MAIN_CARDS';
export const RECEIVE_STAFF_HISTORY_MAIN_CARDS = 'RECEIVE_STAFF_HISTORY_MAIN_CARDS';
export const STAFF_HISTORY_MAIN_CARD_FETCHING = 'STAFF_HISTORY_MAIN_CARD_FETCHING';
export const STAFF_HISTORY_MAIN_CARD_IS_EMPTY = 'STAFF_HISTORY_MAIN_CARD_IS_EMPTY';
